task/03-components
Allocene/fe-react-2024 pull request #3
Opened 2024-05-01 10:24 UTC by Allocene

- [ ]  Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  The ProductsList component correctly receives product data as props.
- [ ]  ProductCard component created and renders a single product.
- [ ]  Header and Footer elements are present.
- [ ]  ProductList displays right on mobile devices
- [ ]  The Header component has clickable elements that toggle the display between the About and ProductsList components.
- [ ]  State management is handled in App.tsx, with state determining which component to show.
- [ ]  LocalStorage added to save items in card after page realod

2024-05-02 15:07 UTC, Allocene commented
I can't figure out how to make the basket in the header show the total number of products...
I am asking for help with this task

2024-05-04 16:18 UTC, Allocene commented
https://allocene.github.io/fe-react-2024/

2024-05-04 17:18 UTC, Fenix4088 requested changes
![Screenshot 2024-05-04 at 17 50 52](https://github.com/Allocene/fe-react-2024/assets/55930010/f6936d6b-3a0c-415b-815d-8cf5d09e24ce)
cursor pointer

2024-05-04 17:18 UTC, Fenix4088 commented on src/App.tsx
> +    const [currentPage, setCurrentPage] = useState('Products');
use enum for `"Products"` and `"About"` string, u are using them all over the app, so it should be a constants
also move this enum into separate file for constants

https://www.typescriptlang.org/docs/handbook/enums.html

2024-05-04 17:18 UTC, Fenix4088 commented on src/App.tsx
> +    const [currentPage, setCurrentPage] = useState('Products');
use a enum as a type for your useState

ALWAYS, set data type to useState generic, it is a good practise
```suggestion
    const [currentPage, setCurrentPage] = useState<string>('Products');
```

2024-05-04 17:18 UTC, Fenix4088 commented on src/App.tsx
> +            {currentPage === 'About' && <About />}
use your enum here

2024-05-04 17:18 UTC, Fenix4088 commented on src/App.tsx
> +            {currentPage === 'Products' && <Products />}
use your enum here

2024-05-04 17:18 UTC, Fenix4088 commented on src/App.tsx
> +            {currentPage === 'About' && <About />}
try to not create sch dynamic variables in component body
you can avoid equality, use hash tables it is better readable use associative array instead

https://www.geeksforgeeks.org/what-are-associative-arrays-in-javascript/

example:
```ts
  switch(type) {
    case 'admin':
      return 'This User is Admin!'
      break
    case 'client':
      return 'This User is Client!'
      break
    case 'salesman':
      return 'This User is Salesman!'
      break
    default:
      return 'Ops, this guy doesn\'t have user profile'
  }
  
  // replace into
  
    const Users = {
    admin: 'This User is Admin!',
    client: 'This User is Client!',
    salesman: 'This User is Salesman!'
  }

  Users[type] || "" // now u can use this 
```
1 - less code
2 - better to read

Also u should move this logic out of react-component scope, it will be better if you will create a helper function

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/CartIcon/CartIcon.tsx
> +            <svg
use SVGR instead native svg code

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/CartIcon/CartIcon.tsx
> +    const [isCartActive, setIsCartActive] = useState(false);
generic type for useState

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/CartIcon/CartIcon.tsx
> +    const [cartItemCount, setCartItemCount] = useState(0);
generic type for useState

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
> +    const [currentPage, setCurrentPage] = useState(1);
generic type

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
> +    }
u can remove this logic, and just use currentPage state to switch between pages

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
> +                ))}
```suggestion
                {Array.from({ length: totalItems }, (_, index) => index + 1)
                    .slice(firstPageIndex - 1, lastPageIndex)
                    .map((number) => (
                        <li key={number}>
                            <Button onClick={() => paginate(number)} className={currentPage === number ? styles.active : styles.nonactive}>
                                {number}
                            </Button>
                        </li>
                    ))}
```

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
> +    const lastPageIndex = Math.min(firstPageIndex + 2, Math.ceil(totalItems / itemsPerPage));
u are using the same logic all over the component
Math.ceil(totalItems / itemsPerPage)
so create variable for this logic, or function

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
> +        if (currentPage > 1) {
try to write condition from negative condition
```suggestion
        if (currentPage <=1) return;
        // otherwise logic 
```

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
> +    };
```suggestion
    const goToNextPage = () => {
        if (currentPage > Math.ceil(totalItems / itemsPerPage))  return;
        
           setCurrentPage(currentPage + 1);
           onPageChange(currentPage + 1);
    };
```

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/header/Header.tsx
> +                        <Link onClick={() => onPageChange('About')} className={styles.li}>
u will use your enum here, mentioned before

2024-05-04 17:18 UTC, Fenix4088 commented on src/index.css
> +/* button:hover {
do u need it?

2024-05-04 17:18 UTC, Fenix4088 commented on src/components/Products/Products.tsx
> +    const itemsPerPage = 8;
const outside of component

2024-05-06 09:37 UTC, Fenix4088 approved these changes

2024-05-06 09:39 UTC, merged