task/05-hooks
Allocene/fe-react-2024 pull request #5
Opened 2024-05-21 20:36 UTC by Allocene

Acceptance Criteria for 1

- [ ]  Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  Simple Pagination component (without ...) is added and works correctly
- [ ]  On the 1st page button Back should be disabled, same as button Forward on the last page
- [ ]  Interaction with pagination should not change or break sorting and filtration.
- [ ]  Category filter (multi-select) is added and works correctly
- [ ]  Sorting input (single select) is added and works correctly
- [ ]  Interaction with filter and sorter should reset pagination and move a user to the 1st page

Acceptance Criteria for 1*

- [ ]  Pagination component with ... is implemented according to [design](https://www.figma.com/design/mRAOMdJiAsD8fHSVnYwUl9/React-web-page?node-id=1-7667&t=vIBPXrxFdrcCGSep-4).
- [ ]  Search input works correctly

2024-05-24 18:55 UTC, Fenix4088 requested changes
please fix this pagination issues before main. review
https://github.com/Allocene/fe-react-2024/assets/55930010/e691f551-58ad-47b0-9ad2-9727f5a8cade

https://github.com/Allocene/fe-react-2024/assets/55930010/81dbdd78-4d08-4d0b-ab3e-cb530aecc4c1

2024-05-24 19:08 UTC, Allocene commented
Added a dependency on changing categories in the Pagination component. In the Products component, reset the current page to the first page when changing the category.

2024-05-25 19:02 UTC, Fenix4088 requested changes

2024-05-25 19:02 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
nice, but move pagination logic into separate hoook
```tsx
const { goToPreviousPage, ....and so on} = usePagination(//some params if u need);
```

2024-05-25 19:02 UTC, Fenix4088 commented on src/components/Pagination/Pagination.tsx
> +                <li className={currentPage === 1 ? styles.disabled : ''}>
DRY- don't repeat yourself
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

```ts
const isFirstPage = currentPage === 1;
```

2024-05-25 19:02 UTC, Fenix4088 commented on src/components/Products/Products.tsx
> +const filterProducts = (products: typeof mock, filter: string, searchQuery: string, selectedCategories: string[]) => {
create a type instead of typeof mock

2024-05-25 19:02 UTC, Fenix4088 commented on src/components/Products/Products.tsx
> +    let filteredProducts = products;
why? filteredProducts i redundant

2024-05-25 19:02 UTC, Fenix4088 commented on src/components/Products/Products.tsx
> +        }
price, newest, oldest 
create enum,

2024-05-25 19:02 UTC, Fenix4088 commented on src/components/Products/Products.tsx
> +    if (searchQuery) {
move logic related with filtering into separate custom hookk

2024-05-26 08:36 UTC, Allocene commented on src/components/Pagination/Pagination.tsx
Done

2024-05-26 13:47 UTC, Fenix4088 approved these changes

2024-05-26 15:32 UTC, merged